const cron = require('node-cron');
const User = require('../models/User');
const VitalEvent = require('../models/VitalEvent');
const Report = require('../models/Report');
const fs = require('fs');
const path = require('path');
// Note: We'll need a mock or real way to trigger the Excel generation to save as file
const ExcelJS = require('exceljs');

/**
 * Find superior officer for a representative
 */
const findSuperior = async (user) => {
  try {
    let superiorRole = "";
    let filter = {};

    if (user.role === 'kebele') {
      superiorRole = 'woreda';
      filter = { 'location.woreda': user.location.woreda, role: 'woreda' };
    } else if (user.role === 'woreda') {
      superiorRole = 'zone';
      filter = { 'location.zone': user.location.zone, role: 'zone' };
    } else if (user.role === 'zone') {
      superiorRole = 'region';
      filter = { 'location.region': user.location.region, role: 'region' };
    } else if (user.role === 'region') {
      superiorRole = 'national';
      filter = { role: 'national' };
    }

    if (!superiorRole) return null;

    const superior = await User.findOne(filter);
    return superior ? superior._id : null;
  } catch (err) {
    console.error('Error finding superior:', err);
    return null;
  }
};

/**
 * Core Automation Logic
 */
const automateReportGeneration = async (period) => {
  console.log(`[Scheduler] Starting automated ${period} report generation...`);
  
  try {
    // Find all officer roles
    const officers = await User.find({ 
      role: { $in: ['kebele', 'woreda', 'zone', 'region'] } 
    });

    for (const officer of officers) {
      // Find superior info
      const superiorId = await findSuperior(officer);
      
      // Create Report record
      await Report.create({
        title: `${period.toUpperCase()} Automated Report - ${officer.username}`,
        type: period,
        generatedBy: officer._id,
        sentTo: superiorId,
        status: superiorId ? 'sent' : 'draft',
        content: {
          automated: true,
          timestamp: new Date(),
          info: `Automated ${period} report generated by system.`
        }
      });
      
      console.log(`Generated and sent ${period} report for ${officer.username}`);
    }
  } catch (error) {
    console.error(`Error in ${period} automation:`, error);
  }
};

// --- SCHEDULES ---

// 1. Daily: at 11:59 PM
cron.schedule('59 23 * * *', () => {
  automateReportGeneration('daily');
});

// 2. Weekly: every Sunday at 11:59 PM
cron.schedule('59 23 * * 0', () => {
  automateReportGeneration('weekly');
});

// 3. Monthly: last day of month at 11:59 PM
cron.schedule('59 23 28-31 * *', () => {
  // Check if it's the last day
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(today.getDate() + 1);
  if (tomorrow.getDate() === 1) {
    automateReportGeneration('monthly');
  }
});

// 4. Yearly: Dec 31st at 11:59 PM
cron.schedule('59 23 31 12 *', () => {
  automateReportGeneration('yearly');
});

console.log('--- Report Automation Scheduler Started ---');
